name: Process Leaderboard Score

on:
  issues:
    types: [opened]

permissions:
  contents: write
  issues: read

jobs:
  process-score:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display issue content
        run: |
          echo "Issue title:"
          echo "${{ github.event.issue.title }}"

          echo "Issue body:"
          echo "${{ github.event.issue.body }}"