name: Update Leaderboard

on:
  repository_dispatch:
    types: [new-score]

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show received data
        run: |
          echo "Player: ${{ github.event.client_payload.player }}"
          echo "Round: ${{ github.event.client_payload.round }}"
          echo "Points: ${{ github.event.client_payload.points }}"